# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmusic', '0003_auto_20170421_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appmusic.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='releasedate',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appmusic.Album'),
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appmusic.Artist'),
        ),
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
