# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmusic', '0004_auto_20170421_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='tags',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='web',
            field=models.URLField(blank=True),
        ),
    ]
